### PR TITLE
Add logging docs (related to `LOG_message` function)

### PR DESCRIPTION
**Pull request by parker-research**

### CODE REVIEW

**Comment by parker-research** [comment]
@JohnathanBurchill, feel free to pull this branch and edit this docs file directly if there's anything you'd change, alter the verbosity of, etc., if you'd like. Comments are good too! 

I'm going to send the link to it in the Discord after merging to serve as the need-to-know introductory point to the new logging system.

**Comment by JohnathanBurchill** [comment]
> @JohnathanBurchill, feel free to pull this branch and edit this docs file directly if there's anything you'd change, alter the verbosity of, etc., if you'd like. Comments are good too!
> 
> I'm going to send the link to it in the Discord to the software team after merging to serve as the need-to-know introductory point to the new logging system.

I've made some minor edits. Revise as desired!

**Review by JohnathanBurchill — DISMISSED** [review]
Approved, in case you are fine with my edits. Revise if desired though.

**Comment by parker-research** [comment]
Awesome changes, thanks!

What was your rationale with this comment?

> Extra debugging information can be logged using `LOG_SEVERITY_DEBUG`. Such
> `LOG_message(...)` statements must be removed from the final version of the
> firmware.

My plan was to leave all the debug `LOG_message` calls in, and just have that log level disabled by default (on boot). May still be helpful to enable it temporarily for certain things/subsystems, if systems aren't working as expected. My understanding is that this is a standard practice in software projects.

**Comment by JohnathanBurchill** [comment]
> Awesome changes, thanks!
> 
> What was your rationale with this comment?
> 
> > Extra debugging information can be logged using `LOG_SEVERITY_DEBUG`. Such
> > `LOG_message(...)` statements must be removed from the final version of the
> > firmware.
> 
> My plan was to leave all the debug `LOG_message` calls in, and just have that log level disabled by default (on boot). May still be helpful to enable it temporarily for certain things/subsystems, if systems aren't working as expected. My understanding is that this is a standard practice in software projects.

Ah - sounds good. Please edit to remove the "must be removed statement". Would be good to mention the use cases for debugging logging though.

**Review by JohnathanBurchill — APPROVED** [review]
Looks good

**Pull request merged**
