### PR TITLE
Telecommands to disable and enable the heartbeat

### PR DESCRIPTION
**Pull request by JohnathanBurchill**
Two convenience telecommands for adjusting the verbosity of the heartbeat telemetry while developing firmware.

### CODE REVIEW

**Comment by DeflateAwning** [comment]
Fantastic! Didn't even know I wanted this! :)

1. Would you mind rebasing off of main (`git checkout main`, `git pull`, `git checkout burchill-heartbeat-telecommands`, `git rebase`, resolve any conflicts [utilize ChatGPT if confused], `git push -f`)? It says there's a confict here, which suggests you just need to rebase.

2. Could you also please change the type of the volatile configuration variable from `int` to `uint8_t`.

Thanks :)

**Comment by JohnathanBurchill** [comment]
Will do. Also, will rename to "heartbeat_on" and "heartbeat_off", slightly shorter versions which start with something more descriptive.

**Comment by JohnathanBurchill** [comment]
Is the workflow at this point to push the commit which addresses your points? Or would I squash first?

**Comment by JohnathanBurchill** [comment]
Went ahead and rebased to fix that conflict.

**Comment by DeflateAwning** [comment]
> Is the workflow at this point to push the commit which addresses your points? Or would I squash first?

Doesn't matter a ton either way here! Seems most open source communities have their own preferences with those practices. 

In larger PRs, I suppose the ideal way is to do an interactive rebase where you squash commits into just a few meaningful commit messages, leaving changes from reviews as an additional commit per review.

**Review by DeflateAwning — APPROVED** [review]

**Comment by DeflateAwning** [comment]
I made a tiny tweak to re-enable the LED blinking regardless of the logging status, as it's a very helpful way to indentify if a task/thread has stalled/failed to yield for a while. Industry-standard practice for RTOS systems.

Squash and merge when you're ready!

**Pull request merged**
