### PR TITLE
Added Enumeration for FLASH driver code to categorize errors

### PR DESCRIPTION
**Pull request by Saksham-P**
### Enum Created:

```enum FLASH_ERRORS {
    FLASH_ERR_OK                    = 0, // No error occurred
    FLASH_ERR_SPI_TRANSMIT_FAILED   = -3, // Error occurred while transmitting SPI signal
    FLASH_ERR_SPI_RECEIVE_FAILED    = -4, // Error occurred while receiving SPI signal
    FLASH_ERR_DEVICE_BUSY_TIMEOUT   = -6, // Took too long for the device to be in standby
    FLASH_ERR_UNKOWN                = -7, // Unknown error occurred (code reached where it shouldn't have been possible)
    FLASH_ERR_STATUS_REG_ERROR      = -8 // Error occurred which was indicated by one of the Status Register Bits.
};
```
The above are the values of the enum that are created to organize the type of errors we can expect in `.../littlefs/flash_driver.c`. The values have been cross-checked with LittleFS return enum values **only** in `lfs.h` file just in case they might conflict later on, so the integer values in the enum are unique to `.../littlefs/flash_driver.c`

### Changes Made:
Most return values have been replaced by the values of above enum, very few have been replaced by a variable, for e.g.:
```
const uint8_t read_status_result = FLASH_read_status_register(hspi, chip_number, status_reg_buffer);
    if (read_status_result != FLASH_ERR_OK) {
        FLASH_deactivate_chip_select();
        return read_status_result;
    }
```
We are returning the variable since it contains the enum value of the error caused within `FLASH_read_status_register()`

### CODE REVIEW

**Comment by DeflateAwning** [comment]
Please rename pull request to describe the change (generally related to the issue that it closes).

**Review by DeflateAwning — CHANGES_REQUESTED** [review]
Decent overall! Main issue is that the return types are `uint`, and you're returning an enum type. The return types should be marked as enums, and intermediate value variables should also be marked as enums.

**Comment by Saksham-P** [comment]
I made the changes to make sure there are no type conflicts,  I was quite surprised that such a major conflict in type wouldn't give a build error.

I have also merged in the latest changes from 'main' branch and incorporated type changes into those. 

As for the whitespaces in `flash_driver.h`, if you like I can have those match the ones in `main` branch. 

Feel free to review the changes made, although I will probably review them myself and most likely wait till Thursday to merge into `main` even if no additional changes are needed.

**Review by DeflateAwning — CHANGES_REQUESTED** [review]
Looks great overall!

Can we please add a new error enum values that's along the lines of `FLASH_ERR_SPI_HAL_TRANSMIT_TIMEOUT` and `FLASH_ERR_SPI_HAL_RECEIVE_TIMEOUT`, which looks at the HAL timeout? It's an important error that indicates a very low-level hardware comms failure. Sorry I didn't suggest it earlier.

**Comment by Saksham-P** [comment]
Yea I could do that, while I do that, should I also incorporate other errors that can happen alongside such as `HAL_ERROR` and `HAL_BUSY`, or do you think we should be fine without those

**Comment by DeflateAwning** [comment]
I think "HAL_TIMEOUT" and then "every other HAL error enum value" is probably adequate. The others generally come as a result of misconfiguration and not from run-time problems

**Review by DeflateAwning — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
