### PR TITLE
Saksham LittleFS library upgrade (v2.9.3 - d01280e)

### PR DESCRIPTION
**Pull request by Saksham-P**
The new version of LittleFS contains updated code about superblocks.

I have also made the changes to the includes from ~~`#include "LittleFS/lfs.h"`~~ to `#include "lfs.h"` since we are using the quotation marks, and the files requesting these libraries are in the same folder as the libraries.

### LittleFS Release Commit Hash [d01280e](https://github.com/littlefs-project/littlefs/commit/d01280e64934a09ba16cac60cf9d3a37e228bb66) :
[0bbb8bc](https://github.com/littlefs-project/littlefs/commit/0bbb8bc) Reorganized external project links a bit
[7808233](https://github.com/littlefs-project/littlefs/commit/7808233) Added a link to mklittlefs
[8336ecd](https://github.com/littlefs-project/littlefs/commit/8336ecd) Added a link to pico-littlefs-usb (FAT12 emulation)
[11b036c](https://github.com/littlefs-project/littlefs/commit/11b036c) Prevented unnecessary superblock rewrites if old version in superblock chain
[25ee90f](https://github.com/littlefs-project/littlefs/commit/25ee90f) Clarified what is accessible at specific superblock offsets in SPEC.md
[a60a986](https://github.com/littlefs-project/littlefs/commit/a60a986) Duplicate the superblock entry during superblock expansion

### CODE REVIEW

**Comment by DeflateAwning** [comment]
Looks good to me. Can you please update the PR title to include the LittleFS release version number and git commit hash that these came from, so that they're in the squashed commit?

**Comment by Saksham-P** [comment]
I updated the original comment and the PR Title, not sure if I want to include all the git hashes from the release to the title.

**Comment by DeflateAwning** [comment]
Just the latest hash in the title is perfect! The hash points to a specific state. The changelog is also valuable, but probably doesn't need to be tracked in here.

Feel free to squash and merge!

**Review by DeflateAwning — APPROVED** [review]
Solid and easy, thanks for doing this!

**Pull request merged**
