### PR TITLE
Rebooting using Telecommand

### PR DESCRIPTION
**Pull request by christopherkinyua**
Implemented System Reboot using Telecommand. I achieved this by using NVIC_SystemReset().

I tried to print to UART a statement to notify the user the board is rebooting but the system reboots before it can get the response to the terminal.

### CODE REVIEW

**Review by DeflateAwning — DISMISSED** [review]
Beautiful and simple, thanks!

Suggestion - add your name to the README in this pull request.

What happens if you do a `DEBUG_uart_print_str("Rebooting by telecommand request..."); HAL_Delay(1000);` ? Might be useful to confirm that the telecommand is received and executed, in case there's a situation where the system appears non-responsive.

**Review by DeflateAwning — APPROVED** [review]

**Review by DeflateAwning — COMMENTED** [review]
Please click "squash and merge" when ready!

**Review by DeflateAwning — APPROVED** [review]
Good changes, thanks! 

I just tacked on another commit that fixes these tiny things:
1. Decreased the delay from 1000ms to 100ms, and explained why its there. Comments are best utilized to explain _why_ code is written. 
2. Removed the `\r` on the UART send. As a matter of standardization, we don't use carriage returns in this project.
3. Fixed the missing `#include <.../debug_uart.h>` so that the clean build succeeds. Funny that it worked at all without this change.

Please "Squash and Merge" then delete the branch when you get a chance!

**Review by DeflateAwning — CHANGES_REQUESTED** [review]
This PR now removes the `scan_i2c_bus` telecommand, and has the `reboot` command in the "SECTION: flash_telecommand_..." comment block.  It also removes an included header. 

Something's gone wrong. Let me know if you need help fixing it. Please check the final diff of the PR to ensure it's ready to merge

**Comment by christopherkinyua** [comment]
I moved the reboot command outside of the flash telecommand section and I added the scan_12c_bus. I have ensured the debug_tools/debug_uart.h header is in the file. Is there anything else that I am missing and is there supposed to be code for the scan_12c_bus code within this branch?

**Comment by DeflateAwning** [comment]
Looking at the diff, this seems like it's getting worse with each commit.

I reverted this branch back to commit 1abc2b46. I also rebased it to main to resolve the merge conflicts. 

You should be good to just Squash and Merge now. If you wanted to make any more changes, make sure to use GitHub Desktop to delete your local branch, and then pull down the latest version of this branch.

**Review by DeflateAwning — APPROVED** [review]

**Comment by christopherkinyua** [comment]
Sure thing, Thanks for the help in fixing this.

**Comment by DeflateAwning** [comment]
No worries! Always happy to help! :)

**Pull request merged**
